version: '3.0'
services:
  redis-for-app:
    image: redis
    hostname: redis-go-app
  go-app:
    image: go-app-redis
    ports:
      - 8082:8080
    environment:
      - REDIS_HOST=redis-go-app
    depends_on:
      - redis-for-app